apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes", "pods"]
  verbs: ["get", "watch", "list"]
