apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: confluent-hk
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
