---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent-sg
  annotations:
    platform.confluent.io/zookeeper-myid-offset: "20"
spec:
  configOverrides:
    peers:
      - server.0=zookeeper-0.zookeeper.confluent-hk.svc.cluster.local:2888:3888
      - server.1=zookeeper-1.zookeeper.confluent-hk.svc.cluster.local:2888:3888
      - server.2=zookeeper-2.zookeeper.confluent-hk.svc.cluster.local:2888:3888
      - server.20=zookeeper-0.zookeeper.confluent-sg.svc.cluster.local:2888:3888
      - server.21=zookeeper-1.zookeeper.confluent-sg.svc.cluster.local:2888:3888
      - server.22=zookeeper-2.zookeeper.confluent-sg.svc.cluster.local:2888:3888:observer
    server:
      - "4lw.commands.whitelist=*"

  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
