apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: wushilin-kafka
spec:
  selector:
    matchLabels:
      app: kafka
  endpoints:
  - port: 7778
    interval: 30s
---
apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: wushilin-zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  endpoints:
  - port: 7778
    interval: 30s
